##############################
##        服务器信息类       ##
##############################

# 服务器侧边栏
Sidebar:
  title: "§6§lMC服务器"
  ip: "www.example.com"

# 设置加入游戏时的标题内容和样式
JoinTitle:
  title: "&b欢迎来到MC服务器！"
  subtitle: "&b祝您游玩愉快!"
  fade-in: 1
  stay: 5
  fade-out: 1

# 设置加入游戏时发送给玩家的信息
JoinMessage:
  - " 欢迎来到MC服务器！ "

# 设置服务器公告
Broadcast:
  enabled: true
  content:
      - "&6 ============================================= "
      - "&6                &l[服务器公告]                  "
      - "&6  遵守法律法规，禁止炸服等恶意破坏服务器的行为！   "
      - "&6 ============================================= "
  interval: 900   # 循环时间间隔（单位：秒）


##############################
##         服务器物品类      ##
##############################

# 初始物品套装
FirstJoinItems:
  - material: STONE_AXE
    amount: 1
    name: "&e石镐"
    lore:
      - "&7新手礼包"
      - "不用做木镐啦！"


##############################
##         服务器规则类      ##
##############################

# 设置玩家重生位置
Spawn:
  WorldSpawn: true    # 设置为 true 时启用世界出生点

Teleport:
  Cooldown: 5         # 传送命令冷却时间（单位：秒）