##############################
##        服务器信息类       ##
##############################

# 服务器侧边栏
Sidebar:
    title: "智算11班MC服务器"
    ip: "www.rtotjn4is.nyat.app"

# 设置加入游戏时的标题内容和样式
JoinTitle:
    title: "&b欢迎来到智算11班MC服务器！"
    subtitle: "&b祝您游玩愉快!"
    fade-in: 1
    stay: 5
    fade-out: 1

# 设置加入游戏时发送给玩家的信息
JoinMessage:
    - " &6&l %player%, 欢迎来到智算11班MC服务器！ "
    - " &6&l 紧密团结在以江书记为核心的团支部周围！"
    - " &6&l 如果遇到Bug请至Github或微信群中留言。"
    - " &6&l Github仓库：https://github.com/5882886/My-Minecraft-Server "

# 设置服务器公告
BroadCast:
    enabled: true
    content:
        - "&6 ============================================= "
        - "&6                &l[服务器公告]                  "
        - "&6  遵守法律法规，禁止炸服等恶意破坏服务器的行为！   "
        - "&6 ============================================= "
    interval: 900   # 循环时间间隔（单位：秒）


##############################
##         服务器物品类      ##
##############################

# 初始物品套装
FirstJoinItems:
    - material: DIAMOND
      amount: 1
      name: "&a钻石"
      lore:
        - "&7新手礼包!"
    - material: GOLD_INGOT
      amount: 5
      name: "&6金锭"
      lore:
        - "&7新手礼包!"
    - material: DIAMOND_SWORD
      amount: 1
      name: "&7石剑"
      lore:
        - "&7新手礼包!"
    - material: WOODEN_AXE
      amount: 1
      name: "&e石镐"
      lore:
        - "&7新手礼包!"

##############################
##         服务器规则类      ##
##############################

# 设置玩家重生位置
Spawn:
    WorldSpawn: true   # 设置为 true 时启用世界出生点
